### ISSUE TITLE
Marks File Format

### ISSUE THREAD

**Issue by fabolhak** [Zuikkis/vdrfuse#1]
Hello, 

thank you for providing this little tool. I would like to use it. However, I'm not sure how the "marks" file should look like. I generated a file with comskip like this:
`comskip --ini=file.ini /some/folder/video01.ts /some/folder`

This generated a `/some/folder/video01.txt` file, which looks like this:

```
FILE PROCESSING COMPLETE 142448 FRAMES AT  2500
-------------------
2220	12477
119372	130266
142447	142448
```

I renamed it to `/some/folder/marks` and then run `./vdrfuse -f -o modules=subdir,subdir=/some/folder mountpoint`. However, when opening `mountpoint` the following message appears:

`invalid marks file, not used`

**Comment by Zuikkis** [comment]
Hi! 

Use output_vdr=1 in comskip.ini, then it should produce correct format. :)

Also I'd like to point out, I later found out that the produced "edited" video file has some issues, because the timestamps are not fixed. Some players play it fine, some show black picture during the clipped part and then continue.

However clipping start and end always works.

**Comment by fabolhak** [comment]
Thank you for the fast reply. I got it working in some players. However, I doesn't seem to work in combination with plex media server transcoder (video does not play back and high CPU usage).
